name: Build Kernel GTA4XLWIFI AOSP NoKSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "🚧 Build gta4xlwifi AOSP NoKSU"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bison \
            flex \
            libssl-dev \
            python3 \
            python-is-python3 \
            libarchive-tools

      - name: Setup toolchain
        run: |
          mkdir -p toolchain
          cd toolchain
          echo 'Downloading antman and syncing...'
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") -S=05012024
          echo 'Patching for glibc...'
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") --patch=glibc
          echo 'Toolchain setup completed'

      - name: Build kernel
        run: |
          python build_kernel.py --target=gta4xlwifi --aosp --no-ksu

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: "Grass-gta4xlwifi-AOSP-NoKSU-Image"
          path: out/arch/arm64/boot/Image
